#catalogo
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (0, 'NA', null);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (1, 'ESTADOS', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (2, 'USUARIO', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (3, 'PERSONA', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (4, 'DOCUMENTO', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (5, 'CORREO', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (6, 'ENVIOS', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (7, 'OFERTAS', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (8, 'PESO', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (9, 'VOLUMEN', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (10, 'SEGURIDAD', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (11, 'CAMION', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (12, 'LICENCIA', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (13, 'CARGA', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (14, 'PERIODO FACTURACION', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (15, 'TIPO CLIENTE', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (16, 'BANCOS', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (17, 'TIPO DE CUENTAS', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (18, 'ESTADO FACTURA', 1);
INSERT INTO catalogo (catalogo_id, catalogo_descripcion, catalogo_estado) VALUES (19, 'TIPO PAGO', 1);

#catalogo_item
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (0, 0, 'NA', null, null);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (1, 1, 'ACTIVO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (2, 1, 'INACTIVO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (3, 1, 'ELIMINADO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (4, 1, 'BLOQUEADO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (5, 1, 'CREADO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (6, 1, 'PENDIENTE', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (7, 1, 'MORA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (8, 2, 'ADMINISTRADOR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (9, 2, 'CONDUCTOR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (10, 2, 'CLIENTE', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (11, 3, 'PERSONA NATURAL', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (12, 3, 'PERSONA JURIDICA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (13, 4, 'RUC', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (14, 4, 'CEDULA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (15, 5, 'HOST', 'smtp.office365.com', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (16, 5, 'PORT', '587', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (17, 5, 'PROTOCOL', 'smtp', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (18, 5, 'USERNAME', 'info@tas-on.com', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (19, 5, 'PASSWORD', 'TasOn01*', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (20, 5, 'DEBUG', 'true', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (21, 5, 'PATH PLANTILLAS', '/opt/plantillas', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (22, 6, 'CREADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (23, 6, 'ASIGNADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (24, 7, 'EN CURSO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (25, 6, 'ENTREGADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (26, 6, 'CANCELADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (27, 6, 'INACTIVA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (28, 6, 'POR COBRAR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (29, 6, 'FINALIZADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (30, 6, 'VENCIDAS', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (31, 7, 'CREADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (32, 7, 'ACEPTADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (33, 7, 'DESECHADAS (NO ACEPTADA)', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (34, 7, 'CANCELADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (35, 7, 'POR PAGAR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (36, 7, 'FINALIZADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (37, 8, 'ton (tonelada)', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (38, 8, 'g', null, 0);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (39, 8, 'kg (kilogramo)', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (40, 8, 'lb (libra)', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (41, 9, 'pie3 (pie cúbico)', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (42, 9, 'm3 (metro cúbico)', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (43, 9, 'gal (galones)', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (44, 10, 'TIPO TIEMPO', 'H', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (45, 10, 'TIEMPO', '60', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (46, 11, 'FURGON CERRADO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (47, 11, 'CARPA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (48, 12, 'C', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (49, 12, 'D', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (50, 12, 'E', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (51, 13, 'CARGA SECA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (52, 13, 'CARGA REFRIGERADA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (53, 13, 'AMBAS', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (54, 7, 'POR ENTREGAR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (55, 7, 'POR ENTREGAR FACTURA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (56, 14, 'DIARIA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (57, 14, 'SEMANAL', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (58, 14, 'QUINCENAL', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (59, 14, 'MENSUAL', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (60, 15, 'EMPRESA CLIENTE', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (61, 15, 'EMPRESA PROVEEDOR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (62, 7, 'GENERAR FACTURA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (63, 6, 'POR DESPACHAR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (64, 6, 'PROCESO DE ENTREGA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (65, 17, 'CUENTA DE AHORROS', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (66, 17, 'CUENTA CORRIENTE', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (67, 16, 'BANCO PICHINCHA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (68, 16, 'PRODUBANCO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (69, 16, 'PACIFICO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (70, 18, 'PREFACTURA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (71, 18, 'FACTURA', null, 1);
#nuevos catalogos ROLES
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (72, 2, 'CONTADOR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (73, 18, 'FACTURAS X PAGAR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (74, 7, 'EN TRANSITO DE PAGO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (75, 2, 'ADMINISTRADOR CLIENTE', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (76, 2, 'EMPRESA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (77, 2, 'CONDUCTOR CLIENTE', null, 1);
#TIPO PAGO
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (78, 19, 'CHEQUE', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (79, 19, 'TRANSFERENCIA', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (80, 19, 'DEPOSITO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (81, 19, 'COMPROBANTE RETENCION', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (82, 2, 'CLIENTE REDUCIDO', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (83, 18, 'FACTURAS X COBRAR', null, 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (84, 7, 'LISTAS PARA EL PAGO', null, 1);

INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (85, 15, 'EMPRESA ADMINISTRADORA', 'NULL', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (86, 5, 'STARTTLS', 'true', 1);
INSERT INTO catalogo_item (catalogo_item_id, catalogo_item_id_catalogo, catalogo_item_descripcion, catalogo_item_valor, catalogo_item_estado) VALUES (87, 10, 'DIAS GESTION ', '10', 1);

  #Localidad
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_code, localidad_localidad_padre, localidad_estado) VALUES (1, 'ECUADOR', 593, 0, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (2, 'AZUAY', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (3, 'BOLÍVAR', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (4, 'CARCHI', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (5, 'CAÑAR', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (6, 'CHIMBORAZO', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (7, 'COTOPAXI', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (8, 'ESMERALDAS', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (9, 'GALÁPAGOS', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (10, 'GUAYAS', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (11, 'IMBABURA', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (12, 'LOJA', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (13, 'LOS RÍOS', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (14, 'MANABI', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (15, 'MORONA SANTIAGO', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (16, 'NAPO', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (17, 'ORELLANA', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (18, 'EL ORO', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (19, 'PASTAZA', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (20, 'PICHINCHA', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (21, 'SANTA ELENA', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (22, 'SANTO DOMINGO DE LOS TSÁCHILAS', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (23, 'SUCUMBIOS', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (24, 'TUNGURAHUA', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (25, 'ZAMORA CHINCHIPE', 1, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (26, 'CAMILO PONCE', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (27, 'CHORDELEG', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (28, 'CUENCA', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (29, 'EL PAN', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (30, 'GIRON', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (31, 'GUACHAPALA', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (32, 'GUALACEO', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (33, 'NABON', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (34, 'OÑA', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (35, 'PAUTE', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (36, 'PAUTE', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (37, 'SAN FERNANDO', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (38, 'SANTA ISABEL', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (39, 'SEVILLA DE ORO', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (40, 'SIGSIG', 2, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (41, 'CALUMA', 3, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (42, 'CHILLANES', 3, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (43, 'CHIMBO', 3, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (44, 'ECHEANDIA', 3, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (45, 'GUARANDA', 3, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (46, 'LAS NAVES', 3, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (47, 'SAN MIGUEL', 3, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (48, 'BOLIVAR', 4, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (49, 'ESPEJO', 4, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (50, 'MIRA', 4, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (51, 'MONTUFAR', 4, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (52, 'SAN PEDRO DE HUACA', 4, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (53, 'TULCAN', 4, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (54, 'AZOGUES', 5, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (55, 'BIBLIAN', 5, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (56, 'CAÑAR', 5, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (57, 'DELEG', 5, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (58, 'LA TRONCAL', 5, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (59, 'SUSCAL', 5, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (60, 'TAMBO', 5, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (61, 'ALAUSI', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (62, 'CHAMBO', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (63, 'CHUNCHI', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (64, 'COLTA', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (65, 'CUMANDA', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (66, 'GUAMOTE', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (67, 'GUANO', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (68, 'PALLATANGA', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (69, 'PENIPE', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (70, 'RIOBAMBA', 6, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (71, 'LA MANA', 7, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (72, 'LATACUNGA', 7, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (73, 'PANGUA', 7, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (74, 'PUJILI', 7, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (75, 'SALCEDO', 7, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (76, 'SAQUISILI', 7, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (77, 'SIGCHOS', 7, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (78, 'ATACAMES', 8, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (79, 'ELOY ALFARO', 8, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (80, 'ESMERALDAS', 8, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (81, 'MUISNE', 8, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (82, 'QUININDE', 8, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (83, 'RIO VERDE', 8, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (84, 'SAN LORENZO', 8, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (85, 'ISABELA', 9, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (86, 'SAN CRISTOBAL', 9, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (87, 'SANTA CRUZ', 9, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (88, 'ALFREDO BAQUERIZO MORENO (JUJAN)', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (89, 'BALAO', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (90, 'BALZAR', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (91, 'COLIMES', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (92, 'DAULE', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (93, 'DURAN', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (94, 'EL TRIUNFO', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (95, 'EMPALME', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (96, 'GENERAL ANTONIO ELIZALDE (BUCAY)', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (97, 'GENERAL VILLAMIL (PLAYAS)', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (98, 'GUAYAQUIL', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (99, 'ISIDRO AYORA', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (100, 'LOMAS DE SARGENTILLO', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (101, 'MARCELINO MARIDUENA', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (102, 'MILAGRO', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (103, 'NARANJAL', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (104, 'NARANJITO', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (105, 'NOBOL', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (106, 'PALESTINA', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (107, 'PEDRO CARBO', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (108, 'SAMBORONDON', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (109, 'SANTA LUCIA', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (110, 'SIMON BOLIVAR', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (111, 'URBINA JADO (SALITRE)', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (112, 'YAGUACHI', 10, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (113, 'ATUNTAQUI', 11, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (114, 'COTACACHI', 11, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (115, 'IBARRA', 11, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (116, 'OTAVALO', 11, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (117, 'PIMAMPIRO', 11, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (118, 'URCUQUI', 11, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (119, 'LOJA', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (120, 'CALVAS', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (121, 'CATAMAYO', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (122, 'CELICA', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (123, 'CHAGUARPAMBA', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (124, 'ESPÍNDOLA', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (125, 'GONZANAMÁ', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (126, 'MACARÁ', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (127, 'PALTAS', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (128, 'PUYANGO', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (129, 'SARAGURO', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (130, 'SOZORANGA', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (131, 'ZAPOTILLO', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (132, 'PINDAL', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (133, 'QUILANGA', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (134, 'OLMEDO', 12, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (135, 'BABAHOYO', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (136, 'BABA', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (137, 'MONTALVO', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (138, 'PUEBLOVIEJO', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (139, 'QUEVEDO', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (140, 'URDANETA', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (141, 'VENTANAS', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (142, 'VÍNCES', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (143, 'PALENQUE', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (144, 'BUENA FÉ', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (145, 'VALENCIA', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (146, 'MOCACHE', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (147, 'QUINSALOMA', 13, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (148, 'PORTOVIEJO', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (149, 'BOLÍVAR', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (150, 'CHONE', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (151, 'EL CARMEN', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (152, 'FLAVIO ALFARO', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (153, 'JIPIJAPA', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (154, 'JUNÍN', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (155, 'MANTA', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (156, 'MONTECRISTI', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (157, 'PAJÁN', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (158, 'PICHINCHA', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (159, 'ROCAFUERTE', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (160, 'SANTA ANA', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (161, 'SUCRE', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (162, 'TOSAGUA', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (163, '24 DE MAYO', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (164, 'PEDERNALES', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (165, 'OLMEDO', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (166, 'PUERTO LÓPEZ', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (167, 'JAMA', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (168, 'JARAMIJÓ', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (169, 'SAN VICENTE', 14, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (170, 'MORONA', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (171, 'GUALAQUIZA', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (172, 'LIMÓN INDANZA', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (173, 'PALORA', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (174, 'SANTIAGO', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (175, 'SUCÚA', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (176, 'HUAMBOYA', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (177, 'SAN JUAN BOSCO', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (178, 'TAISHA', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (179, 'LOGROÑO', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (180, 'PABLO SEXTO', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (181, 'TIWINTZA', 15, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (182, 'TENA', 16, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (183, 'ARCHIDONA', 16, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (184, 'EL CHACO', 16, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (185, 'QUIJOS', 16, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (186, 'CARLOS JULIO AROSEMENA', 16, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (187, 'AGUARICO', 17, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (188, 'LA JOYA DE LOS SACHAS', 17, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (189, 'LORETO', 17, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (190, 'ORELLANA', 17, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (191, 'ARENILLAS', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (192, 'ATAHUALPA', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (193, 'BALSAS', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (194, 'CHILLA', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (195, 'EL GUABO', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (196, 'HUAQUILLAS', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (197, 'LAS LAJAS', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (198, 'MACHALA', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (199, 'MARCABELI', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (200, 'PASAJE', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (201, 'PINAS', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (202, 'SANTA ROSA', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (203, 'ZARUMA', 18, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (204, 'PASTAZA', 19, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (205, 'MERA', 19, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (206, 'SANTA CLARA', 19, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (207, 'ARAJUNO', 19, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (208, 'QUITO', 20, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (209, 'CAYAMBE', 20, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (210, 'MEJIA', 20, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (211, 'PEDRO MONCAYO', 20, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (212, 'RUMIÑAHUI', 20, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (213, 'SAN MIGUEL DE LOS BANCOS', 20, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (214, 'PEDRO VICENTE MALDONADO', 20, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (215, 'PUERTO QUITO', 20, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (216, 'SANTA ELENA', 21, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (217, 'LA LIBERTAD', 21, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (218, 'SALINAS', 21, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (219, 'SANTO DOMINGO', 22, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (220, 'LAGO AGRIO', 23, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (221, 'GONZALO PIZARRO', 23, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (222, 'PUTUMAYO', 23, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (223, 'SHUSHUFINDI', 23, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (224, 'SUCUMBÍOS', 23, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (225, 'CASCALES', 23, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (226, 'AMBATO', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (227, 'BAÑOS DE AGUA SANTA', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (228, 'CEVALLOS', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (229, 'MOCHA', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (230, 'PATATE', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (231, 'QUERO', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (232, 'SAN PEDRO DE PELILEO', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (233, 'SANTIAGO DE PÍLLARO', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (234, 'TISALEO', 24, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (235, 'ZAMORA', 25, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (236, 'CHINCHIPE', 25, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (237, 'NANGARITZA', 25, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (238, 'YACUAMBI', 25, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (239, 'YANTZAZA', 25, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (240, 'EL PANGUI', 25, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (241, 'CENTINELA DEL CÓNDOR', 25, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (242, 'PALANDA', 25, 1);
  INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_localidad_padre, localidad_estado) VALUES (243, 'PAQUISHA', 25, 1);
INSERT INTO localidad (localidad_id, localidad_descripcion, localidad_code, localidad_localidad_padre, localidad_estado) VALUES (244, 'MACAS', 0, 15, 1);

#Conductor
INSERT INTO conductor (conductor_id, conductor_usuario, conductor_cedula, conductor_nombre, conductor_apellido, conductor_tipo_licencia, conductor_telefono, conductor_email, conductor_licencia) VALUES (0, null, null, null, null, null, null, null, null);

#Vehiculo
INSERT INTO vehiculo (vehiculo_id, vehiculo_usuario, vehiculo_modelo, vehiculo_anio, vehiculo_placa, vehiculo_matricula, vehiculo_tipo_carga, vehiculo_tipo_camion, vehiculo_certificado_arcsa, vehiculo_capacidad, vehiculo_tipo_capacidad) VALUES (0, null, null, null, null, null, null, null, null, null, null);

#Cliente
INSERT INTO cliente (cliente_ruc, cliente_tipo_id, cliente_localidad_id, cliente_razon_social, cliente_direccion, cliente_dias_credito, cliente_dias_periodicidad, cliente_tipo_cliente, cliente_comision, cliente_cuenta, cliente_tipo_cuenta, cliente_banco) VALUES ('0991112345001', 12, 208, 'TASON S.A.', 'Antonio Román OE8-213 Y Juán Arauz, Edificio San Fernando, Piso 2', 0, 0, 85, 0, '0', 0, 0);

#Usuario
INSERT INTO usuario (usuario_id_documento, usuario_tipo_documento, usuario_nombres, usuario_apellidos, usuario_celular, usuario_convecional, usuario_ruc, usuario_direccion, usuario_localidad, usuario_nombre_usuario, usuario_contrasenia, usuario_estado, usuario_mail, usuario_tipo_usuario, usuario_principal) VALUES ('1234567890001', 12, 'Administrador', '', '', '022263805', '0991112345001', null, null, 'admin', '9a4fe825a7a5c0931159b3c53580a8f7caafe22d', 1, 'info@tas-on.com', 8, 0);
INSERT INTO usuario (usuario_id_documento, usuario_tipo_documento, usuario_nombres, usuario_apellidos, usuario_celular, usuario_convecional, usuario_ruc, usuario_direccion, usuario_localidad, usuario_nombre_usuario, usuario_contrasenia, usuario_estado, usuario_mail, usuario_tipo_usuario, usuario_principal) VALUES ('1192838192', 14, 'Contador', '', '', '', '0991112345001', null, null, 'contador', '9a4fe825a7a5c0931159b3c53580a8f7caafe22d', 1, 'contador@tas-on.com', 72, 0);

#Secuencia numerica
INSERT INTO secuencia (secuencia_id, secuencia_cliente_id, secuencia_cliente_nemonico, secuencia, secuencia_incremental, secuencia_valor_inicial, secuencia_valor_final) VALUES (0, '0991112345001', 'PFACT', 3, 1, 0, 999999);
INSERT INTO secuencia (secuencia_id, secuencia_cliente_id, secuencia_cliente_nemonico, secuencia, secuencia_incremental, secuencia_valor_inicial, secuencia_valor_final) VALUES (1, '0991112345001', 'FACTU', 0, 1, 0, 999999999);