
export const USER_LOGGED_OUT_SUCCESS = 'USER_LOGGED_OUT_SUCCESS';

export const SELECT_SOLICITUD = 'SELECT_SOLICITUD';

export const FETCHING_DATA="FETCHING_DATA";
export const FETCHING_DATA_SUCCESS="FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE="FETCHING_DATA_FAILURE";

export const FETCHING_DATA_SOLICITUD="FETCHING_DATA_SOLICITUD";
export const FETCHING_DATA_SUCCESS_SOLICITUD="FETCHING_DATA_SUCCESS_SOLICITUD";
export const FETCHING_DATA_FAILURE_SOLICITUD="FETCHING_DATA_FAILURE_SOLICITUD";

export const POSTING_SOLICITUD_OFERTA="POSTING_SOLICITUD_OFERTA";
export const POSTING_SOLICITUD_OFERTA_SUCCESS="POSTING_SOLICITUD_OFERTA_SUCCESS";
export const POSTING_SOLICITUD_OFERTA_FAILURE="POSTING_SOLICITUD_OFERTA_FAILURE";

export const FETCHING_MISFLETES="FETCHING_MISFLETES";
export const FETCHING_MISFLETES_SUCCESS="FETCHING_MISFLETES_SUCCESS";
export const FETCHING_MISFLETES_FAILURE="FETCHING_MISFLETES_FAILURE";

export const FETCHING_DRIVERS="FETCHING_DRIVERS";
export const FETCHING_DRIVERS_SUCCESS="FETCHING_DRIVERS_SUCCESS";
export const FETCHING_DRIVERS_FAILURE="FETCHING_DRIVERS_FAILURE";

export const FETCHING_VEHICLES="FETCHING_VEHICLES";
export const FETCHING_VEHICLES_SUCCESS="FETCHING_VEHICLES_SUCCESS";
export const FETCHING_VEHICLES_FAILURE="FETCHING_VEHICLES_FAILURE";

export const FETCHING_IMAGES="FETCHING_IMAGES";
export const FETCHING_IMAGES_SUCCESS="FETCHING_IMAGES_SUCCESS";
export const FETCHING_IMAGES_FAILURE="FETCHING_IMAGES_FAILURE";

export const NET_IS_OFF="NET_IS_OFF";
export const NET_IS_ON="NET_IS_ON";

export const FETCHING_FCMTOKEN_SUCCESS_DEVICE="FETCHING_FCMTOKEN_SUCCESS_DEVICE";
export const FETCHING_NOTIFICATIONS_SUCCESS="FETCHING_NOTIFICATIONS_SUCCESS";


export const FETCHING_FACTURA="FETCHING_FACTURA";
export const FETCHING_FACTURA_SUCCESS="FETCHING_FACTURA_SUCCESS";
export const FETCHING_FACTURA_FAILURE="FETCHING_FACTURA_FAILURE";

export const POSTING_FACTURA="POSTING_FACTURA";
export const POSTING_FACTURA_SUCCESS="POSTING_FACTURA_SUCCESS";
export const POSTING_FACTURA_FAILURE="POSTING_FACTURA_FAILURE";

export const FETCHING_EMPRESA="FETCHING_EMPRESA";
export const FETCHING_EMPRESA_SUCCESS="FETCHING_EMPRESA_SUCCESS";

export const RECOVERING_PASSWORD_LOADING="RECOVERING_PASSWORD_LOADING";
export const RECOVERING_PASSWORD_SUCCESS="RECOVERING_PASSWORD_SUCCESS";
export const RECOVERING_PASSWORD_FAILURE="RECOVERING_PASSWORD_FAILURE";
export const UPDATING_PASSWORD_LOADING="UPDATING_PASSWORD_LOADING";
export const UPDATING_PASSWORD_SUCCESS="UPDATING_PASSWORD_SUCCESS";
export const UPDATING_PASSWORD_FAILURE="UPDATING_PASSWORD_FAILURE";


export const READING_USUARIO_LOADING="READING_USUARIO_LOADING";
export const READING_USUARIO_SUCCESS="READING_USUARIO_SUCCESS";
export const READING_USUARIO_FAILURE="READING_USUARIO_FAILURE";

export const FETCHING_UTIL_DATA="FETCHING_UTIL_DATA";
export const FETCHING_UTIL_DATA_SUCCESS="FETCHING_UTIL_DATA_SUCCESS";
export const FETCHING_UTIL_DATA_FAILURE="FETCHING_UTIL_DATA_FAILURE";


export const FETCHING_PUBLIC_DATA="FETCHING_PUBLIC_DATA";
export const FETCHING_PUBLIC_DATA_SUCCESS="FETCHING_PUBLIC_DATA_SUCCESS";
export const FETCHING_PUBLIC_DATA_FAILURE="FETCHING_PUBLIC_DATA_FAILURE";


export const FETCHING_CLIENTE_DATA="FETCHING_CLIENTE_DATA";
export const FETCHING_CLIENTE_DATA_SUCCESS="FETCHING_CLIENTE_DATA_SUCCESS";
export const FETCHING_CLIENTE_DATA_FAILURE="FETCHING_CLIENTE_DATA_FAILURE";