export const appConfig = {
  //Produccion
  //apiUrlServicesBase: 'https://www.tas-on.com/tas-on-web-services',
  //Desarrollo
  apiUrlServicesBase: 'http://localhost:8080/tas-on-web-services',
  //QA
  //apiUrlServicesBase: 'http://qa.tas-on.com/tas-on-web-services',
  idEstadoUsuarioActivo: '1',
  idEstadoUsuarioInactivo: '2',
  idEstadoUsuarioEliminado: 3,
  idEstadoUsuarioCreado: 5,
  idEstadoUsuarioPendiente: 6,
  idConductorType: '9',
  idClienteType: 10,
  idUsuarioClienteAdmin: 75,
  idUsuarioClienteReducido: 82,
  idUsuarioConductorAdmin: 77,
  idUsuarioAdmin: 8,
  idUsuarioCliente: 10,
  idUsuarioConductor: 9,
  idUsuarioContador: 72,
  idUsuarioEnviosAdmin: 344,
  idUsuarioEnvios: 345,
  idUsuarioClienteAdminEnvios: 346,
  idUsuarioVendedorCliente: 349,
  idEmpresaType: 76,
  idEmpresaCliente: 60,
  idEmpresaProveedor: 171,
  idRuc: 13,
  idCedula: 14,
  idPersonaNatural: 11,
  idPersonaJuridica: 12,
  idCatalogoPersona: '3',
  idCatalogoDocumento: '4',
  idLocalidadPadreEcuador: '1',
  idCatalogoEnvios: 6,
  idCatalogoCamion: '11',
  idCatalogoLicencia: '12',
  idCatalogoCarga: '13',
  idCatalogoPeriodo: '14',
  idCatalogoTipoEmpresa: 15,
  idCatalogoBanco: 16,
  idCatalogoTipoCuenta: 17,
  idCatalogoTipoPago: 19,
  idCatalogoTipoCompra: 24,
  idCatalogoOfertas: 7,
  idCatalogoRenta: 25,
  idCatalogoIVA: 26,
  idCatalogoTipoProducto: 27,
  idCatalogoMedioDifusion: 28,
  idCatalogoItemVendedor: 274,
  idCatalogoTiposSubasta: 32,
  idSubastaInversaAbierta: 290,
  idSubastaInversaValorObjetivo: 291,
  idPrecioFijo:  295,
  estadoSolicitudEnvioActiva: 22,
  estadoSolicitudCancelada: 26,
  estadoSolicitudEnvioAsignada: 23,
  estadoSolicitudEnvioPorDespachar: 63,
  estadoSolicitudPorPagar: 28,
  estadoSolicitudEnvioEntregada: 25,
  estadoTodasSolicitudesEntregadas: 999,
  estadoSolicitudEnvioProcesoEntrega: 64,
  estadoSolicitudPagadas: 29,
  idCatalogoPesos: '8',
  idCatalogoVolumen: '9',
  idTipoClienteEmpresaCliente: '60',
  idTipoClienteEmpresaTransportista: '61',
  idTipoClienteEmpresaTransportistaIndependiente: '276',
  idTipoEmpresaProveedor: 171,
  idTipoClienteProveedorIndependiente: '62',
  idCatalogoPeriodoFacturacion: '14',
  msgRequerido: 'Campo requerido',
  msgCorreoValido: 'Ingresar un correo válido',
  msgSoloNumeros: 'Ingresar solo números',
  msgSoloLetras: 'Ingresar solo letras',
  msgLetrasNumerosGuion: 'Ingresar solo letras o números y guion bajo',
  msgNumeroDosDecimales: 'Ingrese valores con hasta dos decimales',
  ofertasEstadoCreada: 31,
  ofertasEstadoAceptada: 32,
  ofertaEstadoCurso: 24,
  ofertaEstadoPorEntregar: 54,
  ofertaEstadoCancelada: 34,
  ofertaEstadoFinalizada: 36,
  ofertaEstadoCobrar: 35,
  ofertaEstadoListasPago: 84,
  ofertaEstadoGenerarFactura: 62,
  ofertaEstadoTransitoPago: 74,
  tipoPagoRetencion: 81,
  tipoPagoNotaCredito: 293,
  msgEmailUnico: 'El correo electrónico ya se encuentra registrado.',
  msgEmailValido: 'La dirección ingresada no es un correo valido.',
  msgUserNameUnico: 'El nombre de usuario ya se encuentra registrado.',
  msgNumDocUnico: 'El número de documento ingresado ya se encuentra registrado.',
  msgRUCUnico: 'El RUC de la empresa ya se encuentra registrado.',
  msgIdUsuarioUnico: 'El identificador del usuario ya se encuentra registrado.',
  msgIdUsuarioTamanio: 'El identificador del usuario debe tener 10 o 13 dígitos.',
  msgSoloNumerosDecimales: 'Ingresar un valor hasta con dos decimales. Ejemplo: 99.99',
  msgPlacaUnico: 'Ingresar el número de placa ya se encuentra registrado.',
  facturaEstadoPre: 70,
  facturaEstadoFinal: 71,
  facturaPorPagar: 73,
  facturaPorCobrar: 83,
  idFactGastoPendientePago: 172,
  idFactGastoListaPago: 173,
  idFactGastoPagadas: 174,
  idPagoNormal: 160,
  idPagoInmediato: 161,
  formatoFechaHoraSegundos: 'dd/MM/yyyy HH:mm:ss',
  formatoFechaHoraURL: 'yyyy-MM-dd HH:mm:ss',
  formatoFechaURL: 'dd-MM-yyyy',
  formatoFechaHora: 'dd/MM/yyyy HH:mm',
  formatoFecha: 'dd/MM/yyyy',
  formatoFechaDatePicker: 'dd/mm/yyyy', //mm es lo correcto para mes en este caso
  rucTas: '1792885256001',
  PUBLIC_USER: 'public',
  PUBLIC_PASSWORD: '9a4fe825a7a5c0931159b3c53580a8f7caafe22d',
  estadoFotoRecoleccion: 1,
  estadoFotoEntrega: 2,
  idEnvioPorRecibir: 338,
  idEnvioPorEntregar: 339,
  idEnvioCompletado: 340,
  idEstadosEnvios: 33,

  idVisitaPedidoTomado: 351,
  idVisitaPendiente: 350
};
